## MONGO DB 

- Although we have data but in this project we will fetch the data from the MongoDB cluster set up in AWS 
- so in this notebook we will push the data in the mongoDB

In [8]:
import pandas as pd
import pymongo

In [2]:
df = pd.read_csv('data.csv')

In [5]:
df.shape

(381109, 12)

In [7]:
df.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [9]:
# df should be converted into dict before we push it to mongodb
#in monfoDb we have to push the data in the form of k:v pair 

data = df.to_dict(orient='records')

In [11]:
#data

In [ ]:
#MONGODB CREDENTIALS
DB_NAME = "Proj1"
COLLECTION_NAME = "Proj1-Data"
CONNECTION_URL = "mongodb+srv://aggravish_db_user:vuFhN4C5ZqOZjud1@cluster0.fqipr9m.mongodb.net/?appName=Cluster0"

# above, either remove your credentials or delete the mongoDB resource bofore pushing it to github.

In [ ]:
#MONGODB SETUP
#Project->DataBase->Collection (this is the hierarchy)
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [14]:
# Uploading data to MongoDB
#data is in the form of a dictionary and .insert_many will take these k:v pairs and push the data in the mongoDB
rec = collection.insert_many(data)

In [15]:
# Load back data from mongodb

df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,6a7343399c277410f296da30,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,6a7343399c277410f296da31,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0